name: Issues
on:
  issues:
    types: [opened]
jobs:
  mostrar-evento:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar información del issue
        run: |
          echo "Título: ${{ github.event.issue.title }}"
          echo "Número: ${{ github.event.issue.number }}"
          echo "Autor: ${{ github.event.issue.user.login }}"
          echo "Body:"
          echo "${{ github.event.issue.body }}"
